In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

In [5]:
digits=load_digits()

In [6]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
model_lr=LogisticRegression()
model_SV=SVC()
model_RF=RandomForestClassifier()

In [8]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [19]:
model_lr.fit(X_train,y_train)

C:\Users\hazik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
model_lr.score(X_test,y_test)

0.9666666666666667

In [21]:
model_SV.fit(X_train,y_train)

SVC()

In [22]:
model_SV.score(X_test,y_test)

0.9944444444444445

In [23]:
model_RF.fit(X_train,y_train)

RandomForestClassifier()

In [24]:
model_RF.score(X_test,y_test)

0.9703703703703703

In [46]:
def Model_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [26]:
from sklearn.model_selection import KFold

In [47]:
kf=KFold(n_splits=10)

In [42]:
Model_score(LogisticRegression(),X_train,X_test,y_train,y_test)

Model Score is: 0.9666666666666667


C:\Users\hazik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [43]:
Model_score(SVC(),X_train,X_test,y_train,y_test)

Model Score is: 0.9944444444444445


In [44]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=10)

In [58]:
scores_lr=[]
scores_sv=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_sv.append(Model_score(SVC(),X_train,X_test,y_train,y_test))
    scores_lr.append(Model_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
    scores_rf.append(Model_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [57]:
scores_lr

[0.9055555555555556,
 0.9722222222222222,
 0.8833333333333333,
 0.9555555555555556,
 0.9444444444444444,
 0.9555555555555556,
 0.95,
 0.9329608938547486,
 0.88268156424581,
 0.9273743016759777]

In [59]:
scores_rf

[0.9166666666666666,
 0.9777777777777777,
 0.9166666666666666,
 0.9111111111111111,
 0.95,
 0.9722222222222222,
 0.9833333333333333,
 0.9664804469273743,
 0.9441340782122905,
 0.9217877094972067]

In [60]:
scores_sv

[0.9444444444444444,
 1.0,
 0.9333333333333333,
 0.9833333333333333,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9664804469273743,
 0.9497206703910615]

In [61]:
from sklearn.model_selection import cross_val_score

In [63]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [64]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91666667, 0.89166667, 0.94428969, 0.96100279, 0.93036212])